### ISSUE TITLE
A library relies on native code that's not available. Or only works properly when the sketch is run as a 32-bit application

### ISSUE THREAD

**Issue by benfry** [processing/processing-video#90]
Moved from https://github.com/processing/processing/issues/5453

**Comment by shiffman** [comment]
@ArthurSongChina, thanks for message! I'm not able to reproduce the error. I noticed your Processing version is 3.0.1, can you try updating to the latest Processing? (And check for any updates for the video library in the contributions manager too.)

**Comment by ArthurSongChina** [comment]
@shiffman , Thank you for your instruction! I have updated my Processing to the version 3.3.7.
![2018-03-29 12 05 59](https://user-images.githubusercontent.com/30542763/38069568-9c14fd0e-3349-11e8-88c6-2f4bdfa089f7.png)
And I tried to remove the Video library and install again(version:Video 1.0.1) ,but I still have the same problem.
![2018-03-29 12 15 48](https://user-images.githubusercontent.com/30542763/38069812-fdae5cee-334a-11e8-8f5e-aec1b29cbaa9.png)
![2018-03-29 12 17 07](https://user-images.githubusercontent.com/30542763/38069834-1ea6dca0-334b-11e8-8b4e-d57ae6e70c5b.png)

**By the way, your processing tutorial on Youtube is great.**

**Comment by ludcila** [comment]
I was getting this exact same error in v3.3.7, and it turned out to be because I had non-ASCII characters in my Processing path. If that's your case, try changing the sketchbook location to something like C:\Processing in File > Preferences.

It looks like it's an old issue with a different error message...?
https://github.com/processing/processing/issues/2472
https://github.com/processing/processing-video/issues/10

**Comment by ArthurSongChina** [comment]
@ludcila  Thank you for your instruction. Even thought My laptop is MacBook, but I understand that the problem was that I have not put the sketchbook location in the system hard disk。

**Comment by yurikleb** [comment]
Hey All, I'm getting a same error on Ubuntu 16.04 (Running processing 3.3.7):
`UnsatisfiedLinkError: Error looking up function 'gst_date_get_type': /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0.803.0: undefined symbol: gst_date_get_type
A library relies on native code that's not available.
Or only works properly when the sketch is run as a 32-bit application.`

Any ideas how to solve this?
Tanks!

**Comment by yurikleb** [comment]
ok I solved all the errors by installing: 
` sudo apt-get install libgstreamer-plugins-base0.10-dev libgstreamer0.10-dev libglib2.0-dev`
and 
` sudo apt-get install libgstreamer-plugins-base0.10-dev libgstreamer0.10-dev libglib2.0-dev`

Also had to provide the full path of the video (putting it inside "data" folder didn't work).

But the video still doesn't play. tried both .mp4 and .mov files.

**Comment by neilcsmith-net** [comment]
@yurikleb try the download at https://github.com/processing/processing-video/releases

**Comment by danragan** [comment]
I'm receiving the same issue, but it's not related to non-ASCII characters. Here's a screen recording of the issue -->  https://www.useloom.com/share/e6900e3f5d4342418a7700bdbb35e79f

For reference, I'm using Windows 10 and recently started using a second user account for all my VJ / interactive work. Not sure if this has anything to do with it?

**Comment by vepicurean** [comment]
I'm trying to confirm if the current Processing 3.4 video library 1.0.1 supports Gstreamer 1.0 or not with Linux? 

It's not clear in the documentation if the video library 1.0.1 is only for use the very old (unmaintained) GStreamer 0.10 (which most Linux distributions no longer have in their repositories, and that makes sense to me). 

From the notes in the Processing wiki, I'm seeing that to use gstreamer 1.0 API with Processing 3.4, I should install this [video library Release 3 (version 2.0-beta1)](url) on Linux (Ubuntu 18.04)? Can someone please confirm if my interpretation is correct?

If yes, are there detailed instructions for installing the Release 3 (version 2.0-beta1)?

I currently have the video library 1.0.1 on Processing 3.4 on Ubuntu Linux 16.04 and that doesn't seem to work with gstreamer 1.0 API from the error messages I'm seeing in the Processing 3.4 console.

**Comment by vepicurean** [comment]
Can someone let me know on the above issue with regard to Processing 3.4 and the Gstreamer 0.10 and 1.0 APIs.  It's important to determine whether we should continue to do the development of our app with Processing or not, given the fact that GStreamer 1.0 has been around for a very long time and Processing doesn't seem to have a firm roadmap to work with GStreamer 1.0.

**Comment by neilcsmith-net** [comment]
@vepicurean you're correct that only version 2.0-beta1 supports GStreamer 1.x (I'm the maintainer of the underlying [GStreamer Java](https://github.com/gstreamer-java/gst1-java-core) bindings).  You should be OK with the beta version of the video library.  You could also look at [PraxisLIVE](https://www.praxislive.org) (and the PraxisCORE runtime), which might offer a more stable and efficient way of using Processing and GStreamer 1.x together.  Or if you're comfortable with Java code you could use the bindings directly, with or without Processing.  Depends what you're building really!  I can help you with the non-Processing elements of this - contact me via the PraxisLIVE website.

**Comment by vepicurean** [comment]
Thanks for the reply @neilcsmith-net 

Maybe it's me just completely missing how to properly install the version 2.0-beta1 video library on Processing 3.4.  I tried this procedure https://github.com/processing/processing/wiki/How-to-Install-a-Contributed-Library to install the version 2.0-beta1 video library manually, but no success getting the library to work (probably something I'm not doing right given the instructions are straight forward for manual install of a library on Processing.  But maybe I'm putting things in the wrong place).  

If I can at least get the instructions/procedure to manually install version 2.0-beta1 video library so that all apps can use the version 2.0-beta1 video library on Processing 3.4 and then test this works with GStreamer 1.0 on our Ubuntu 18.04 server, then I can see how much additional work would need to be done with our Processing based app.

Thanks for the information on PraxisLive.  I'll research it and discuss with the team and get back to you.

Thanks for your help and time.

**Comment by vepicurean** [comment]
If anyone has details instructions to install the version 2.0-beta1 video library on Processing 3.4 it would be appreciated. Thanks.

**Comment by lessthanoptimal** [comment]
Any progress on this? I'm trying to update my contributed computer vision library (BoofCV) but I can't test many of the old/new features without a functioning webcam. I'm running Ubuntu 18.04 on a x64 system.

**Comment by anarchitectures** [comment]
Someone please fix this issue. Like others, I can't use videos in my processing.video sketches nor can I install any of the forked libraries on my system (Ubuntu).

**Comment by meniossin** [comment]
> If anyone has details instructions to install the version 2.0-beta1 video library on Processing 3.4 it would be appreciated. Thanks.

Hey there everyone , newcomer here.  I tried today replacing the old video library(1.0.1 installed from Processing) with the beta version of the library, found here as an alternative to this problem:[(https://github.com/processing/processing-video/releases/tag/r3-v2.0-beta1)]

I replaced the video folder from the `sketchbook/libraries` directory, with the new video folder found after extracting the zip file  and restarted Processing.

While this fix worked at the beginning and I was able to establish a video stream when I run a simple script , when I tried adding some extra functionality in the script and rerun it, I got the following error : 
`BaseSrc: [autovideosrc0-actual-src-v4l] : Internal data stream error.`

 I tried refactoring my code back to the first simple script that just captured the video stream but still getting the error above.
Any idea if this is related with this issue ?
Should I open this as a new issue, i.e stating that it's for the v2.0-beta1 version exclusively  ?
Are there any news regarding the support of this video library for Processing 3.5.3 and Gstreamer 1.x in Linux x64 systems ? (I'm running on Ubuntu 18.04 64-bit).

Thanks.

**Comment by neilcsmith-net** [comment]
>  when I tried adding some extra functionality in the script and rerun it, I got the following error :
`BaseSrc: [autovideosrc0-actual-src-v4l] : Internal data stream error.`

@meniossin what does this mean exactly?  What did you add specifically, and anything calling into the Video library?  I'd be interested if you can replicate in PraxisLIVE too - that might narrow down the cause of the issue.

**Comment by meniossin** [comment]
Hey @neilcsmith-net , I'm posting the original code here (that was my script at the beginning). The first part is just getting the video stream, detecting the motion of pixels  and if they move , display them as black.  > 

`import processing.video.*;

Capture video;

// Previous Frame
PImage prevFrame;
// How different must a pixel be to be a "motion" pixel
float threshold = 50;

void captureEvent(Capture video){
   // Save previous frame for motion detection!!
  prevFrame.copy(video, 0, 0, video.width, video.height, 0, 0, video.width, video.height); // Before we read the new frame, we always save the previous frame for comparison!
  prevFrame.updatePixels();  // Read image from the camera
  video.read();
}

void setup() {  
  size(640,480);
  //ps = new ParticleSystem(new PVector(width/2, 50));

  video = new Capture(this, width, height, 60);
  video.start();
  prevFrame = createImage(video.width, video.height, RGB);
  
}

void draw(){
  loadPixels();
  video.loadPixels();
  prevFrame.loadPixels();

  // Begin loop to walk through every pixel
  for (int x = 0; x < video.width; x ++ ) {
    for (int y = 0; y < video.height; y ++ ) {

      int loc = x + y*video.width;            // Step 1, what is the 1D pixel location
      color current = video.pixels[loc];      // Step 2, what is the current color
      color previous = prevFrame.pixels[loc]; // Step 3, what is the previous color

      // Step 4, compare colors (previous vs. current)
      float r1 = red(current); 
      float g1 = green(current); 
      float b1 = blue(current);
      float r2 = red(previous); 
      float g2 = green(previous); 
      float b2 = blue(previous);
      float diff = dist(r1, g1, b1, r2, g2, b2);

      // Step 5, How different are the colors?
      // If the color at that pixel has changed, then there is motion at that pixel.
      if (diff > threshold) { 
        // If motion, display black
        pixels[loc] = color(0);
       // ps.addParticle();
       // ps.run();
      } else {
        // If not, display white
        pixels[loc] = current;
        
      }
    }
  }
  updatePixels();
  
}`

Then I tried to add a particle system so for each pixel of the iteration I could create a particle motion trail phenomenon.
That's the rest of the code I added and got the error commented above.

`// A class to describe a group of Particles
// An ArrayList is used to manage the list of Particles 

/*class ParticleSystem {
  ArrayList<Particle> particles;
  PVector origin;

  ParticleSystem(PVector position) {
    origin = position.copy();
    particles = new ArrayList<Particle>();
  }

  void addParticle() {
    particles.add(new Particle(origin));
  }

  void run() {
    for (int i = particles.size()-1; i >= 0; i--) {
      Particle p = particles.get(i);
      p.run();
      if (p.isDead()) {
        particles.remove(i);
      }
    }
  }
}


// A simple Particle class

class Particle {
  PVector position;
  PVector velocity;
  PVector acceleration;
  float lifespan;

  Particle(PVector l) {
    acceleration = new PVector(0, 0.05);
    velocity = new PVector(random(-1, 1), random(-2, 0));
    position = l.copy();
    lifespan = 255.0;
  }

  void run() {
    update();
    display();
  }

  // Method to update position
  void update() {
    velocity.add(acceleration);
    position.add(velocity);
    lifespan -= 1.0;
  }

  // Method to display
  void display() {
    stroke(255, lifespan);
    fill(255, lifespan);
    ellipse(position.x, position.y, 8, 8);
  }

  // Is the particle still useful?
  boolean isDead() {
    if (lifespan < 0.0) {
      return true;
    } else {
      return false;
    }
  }
}*/`

**Comment by neilcsmith-net** [comment]
@meniossin well, this line is suspicious -

```
video = new Capture(this, width, height, 60);
```

Why did you add the 60 in there?  I get the same error with that - try just

```
video = new Capture(this, width, height);
```

By adding the `60` in you're telling the library you want 60fps _or nothing_.  Mind you, it might be better if the pipeline in the Capture component in the library was updated to also use a `videorate` element, which is what the PraxisLIVE equivalent does.

**Comment by meniossin** [comment]
Hey @neilcsmith-net  you were right, 
It was the 60fps parameter. I changed it to the new line you've written above and it works now.
Sorry for this mess.
Cheers!

**Comment by sovello** [comment]
Anyone found a solution to fix this issue.
Looks like Processing 3.5.3 doesn't recognize the newer (beta) version of the video library as it is suggested as an alternative in this thread.

**Comment by codeanticode** [comment]
@sovello [v2.0 beta3](https://github.com/processing/processing-video/releases/tag/r5-v2.0-beta3) should work on windows, let me know if it does for you.

**Comment by sovello** [comment]
Thanks @codeanticode. Actually this worked through tweaking my Java setup and one or two other configs. (Too bad I didn't document. I may put them here once I remember what I did exactly).

**Comment by max246** [comment]
@codeanticode  Yep the beta version worked for Linux as well :) thanks!

**Comment by codeanticode** [comment]
@max246 great, thanks for letting me know! Sounds like this issue could be closed?

**Comment by max246** [comment]
It think so, probably you can release the beta to be "final" :)

**Comment by codeanticode** [comment]
Closing, as this issue has been solved in beta3.

**Comment by zanghsgr** [comment]
how you guys sovle the problem?i dont quite understand.
 its 2021/5/28 i still have the same problem. i download the library properly.but it just 
![SharedScreenshot](https://user-images.githubusercontent.com/82210033/119912365-ef3d5480-bf8d-11eb-8f03-dea1fd734467.jpg)
![SharedScreen２２shot](https://user-images.githubusercontent.com/82210033/119912370-f06e8180-bf8d-11eb-875d-b85fe5eee8bf.jpg)
![１１](https://user-images.githubusercontent.com/82210033/119912374-f1071800-bf8d-11eb-98c3-d6cc183f768f.jpg)
![２２](https://user-images.githubusercontent.com/82210033/119912376-f2384500-bf8d-11eb-9a8c-804a940b7a7a.jpg)



cant work!

**Comment by lub34** [comment]
Any update? Im having the same issue on my Jetson Nano, on which Im running Ubuntu 18.04
